// Writes src/version.ts from package.json before every build, so the version the server reports is
// a constant in the code rather than a file read at run time (which a Cloudflare Worker cannot do).
import { readFileSync, writeFileSync } from "node:fs";

const { version } = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
writeFileSync(
  new URL("../src/version.ts", import.meta.url),
  `// Generated by scripts/write-version.mjs from package.json. Do not edit.\nexport const PACKAGE_VERSION = "${version}";\n`
);
